title: "Cloud Engineering Learning Path"
description: "A step-by-step resource guide to transition from zero tech background to cloud engineering."
baseurl: ""  # Use "/" if deploying to a subpath, or keep empty if root
url: "https://mrcloudchase.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap

# Update to correctly point to your layouts directory
layouts_dir: "_layouts"

# Specify the CSS directory
sass:
  sass_dir: "_sass"
  style: compressed

# Point to assets correctly
assets:
  css:
    - "/assets/css/style.css"

# Paths for learning modules and paths navigation
collections:
  paths:
    output: true
    permalink: /paths/:path/
  modules:
    output: true
    permalink: /paths/:path/:module/
