title: "Self-Learning Paths"
description: "Free resources and learning paths for cloud, AI/ML, and DevOps."
author: Cloud Chase
baseurl: ""
url: "https://your-site.github.io"
theme: minima
plugins:
  - jekyll-sitemap  # Automatically generates a sitemap for SEO purposes
  - jekyll-feed  # Adds RSS feed functionality for the blog